# Основные настройки приложения
spring:
  application:
    name: Survey-Flow-Bot
  autoconfigure:
    exclude:
      - org.telegram.telegrambots.longpolling.starter.TelegramBotStarterConfiguration

server:
  port: ${PORT} # Render.com сам подставит порт

# Настройки бота
telegram:
  bot:
    token: ${BOT_TOKEN}
    username: ${BOT_USERNAME}
    # ВАЖНО: Это БАЗОВЫЙ URL без слеша в конце
    webhook-url: ${WEBHOOK_BASE_URL}
    # ВАЖНО: Это путь, начинающийся со слеша
    webhook-path: /webhook

# Логирование
logging:
  level:
    io.telegram.bot: DEBUG
    org.springframework.web: INFO